const fs = require('fs')
const jwt = require('jsonwebtoken')
const express = require('express')
const path = require('path')
const router = express.Router()

// loading the private key which generated from openssl
const privateKey = fs.readFileSync(
  path.resolve('I:/Zindhu/StarMarket/certs/private.pem'),
  'utf-8'
)
//loading the public key which generated by openssl
const publicKey = fs.readFileSync(
  path.resolve('I:/Zindhu/StarMarket/certs/public.pem'),
  'utf-8'
)

// const privateKey = `-----BEGIN EC PRIVATE KEY-----MHcCAQEEIEc+IuO3VhVr7V7xADnJHJlVm8MnbIsfWPL6Brktbd0PoAoGCCqGSM49
// AwEHoUQDQgAEq//I76hvriuYv3+SqgrjSCl4HDv8IbVib55enUAssjDieoGeoM5M4nqtKS28h00bVeWRJ+DYEUXDOmpDH4X19g==-----END EC PRIVATE KEY-----`
// const publicKey = `-----BEGIN PUBLIC KEY-----MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEq//I76hvriuYv3+SqgrjSCl4HDv8IbVib55enUAssjDieoGeoM5M4nqtKS28h00bVeWRJ+DYEUXDOmpDH4X19g==-----END PUBLIC KEY-----`

let { accessToken } = {}
router.post('/verifyToken', (req, res) => {
  res.json(privateKey)
})

// generate jwt token with prvt key
router.post('/generateToken', (req, res) => {
  const payload = req.body

  const token = jwt.sign(payload, privateKey, {
    algorithm: 'ES256'
    // expiresIn: '1h'
  })
  accessToken = token
  res.status(201).json({ token })
})

router.post('/verify', (req, res) => {
  const token = req.body
  try {
    const decodedToken = jwt.verify(token.token, publicKey, {
      algorithms: ['ES256'],
      ignoreExpiration: false
    })
    const decoded = jwt.decode(token, { complete: true })
    res.status(200).json({ valid: true, decodedToken })
  } catch (err) {
    res.status(401).json({ valid: false, error: err.message })
  }
})

router.post('/login', (req, res) => {
  // req.headers.authorization = `Bearer ${accessToken} `
  // req.headers.accept = 'application/json'

  res.status(200).json({ accessToken: '23423' })
})

module.exports = router
